all:
  hosts:
    servidor_app:
      ansible_host: 0.0.0.0        # reemplazar con la IP del servidor (EC2 u otro)
      ansible_user: ubuntu
      ansible_ssh_private_key_file: ~/.ssh/pokie_key.pem
      ansible_python_interpreter: /usr/bin/python3
